### ISSUE TITLE
perform_get_instruction_low_level_il - NotImplementedError

### ISSUE THREAD

**Issue by lucasduffey** [lucasduffey/smaliBinja_python#36]
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 315, in 'calling callback function'
  File "/home/user/binaryninja/plugins/../python/binaryninja/__init__.py", line 6095, in _get_instruction_low_level_il
    LowLevelILFunction(self, core.BNNewLowLevelILFunctionReference(il)))
  File "/home/user/binaryninja/plugins/../python/binaryninja/__init__.py", line 6490, in perform_get_instruction_low_level_il
NotImplementedError

**Comment by lucasduffey** [comment]
perform_get_instruction_low_level_il IS implemented in both APKView and DexView.

Why is this error spammed?

**Comment by lucasduffey** [comment]
![not_implemented_error](https://cloud.githubusercontent.com/assets/596937/18965146/cd72ad28-8630-11e6-8a48-55d2754ad461.png)

**Comment by lucasduffey** [comment]
FIXED: perform_get_instruction_low_level_il needs to be implemented in the ARCH
