### ISSUE TITLE
AttributeError: dex_class instance has no attribute 'interfaces_off'

### ISSUE THREAD

**Issue by lucasduffey** [lucasduffey/smaliBinja_python#37]
Exception in thread Thread-6:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/user/.binaryninja/plugins/smaliBinja/dexFile.py", line 1320, in create_all_dex_classes
    dex_classes[classId].update_binja(self)
  File "/home/user/.binaryninja/plugins/smaliBinja/dexFile.py", line 337, in update_binja
    offset = self.interfaces_off + 4 # struct.calcsize("I") == 4
AttributeError: dex_class instance has no attribute 'interfaces_off'

**Comment by lucasduffey** [comment]
if dex_class is instantiated, and fails returning None - this may cause it's attributes to not work properly

**Comment by lucasduffey** [comment]
subsequent usage checked object against "None", but issue remains

**Comment by lucasduffey** [comment]
wrapped in try/except but problem still remains
